[package]
name = "cep85-test-contract"
version = "1.0.0"
edition = "2018"

[[bin]]
name = "cep85_test_contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[dependencies]
cep85 = { path = "../contract" }
casper-contract = "3.0.0"
casper-types = "3.0.0"
