[package]
name = "cep85-test-contract"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license-file.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
cep85 = { path = "../contract" }
casper-types.workspace = true
casper-contract = { workspace = true }

[[bin]]
name = "cep85_test_contract"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
default = ["cep85/contract-support"]
