[package]
name = "tests"
version.workspace = true
edition.workspace = true

[dev-dependencies]
casper-types = { workspace = true, features = ["std"] }
casper-event-standard.workspace = true
cep85 = { path = "../contracts/contract", default-features = false }
cep85-test-contract = { path = "../contracts/test-contract", default-features = false }
casper-engine-test-support = { version = "8.1.0", default-features = false }
casper-execution-engine = { version = "8.1.0", default-features = false }
casper-storage = { version = "2.0.0", default-features = false }
serde_json = { version = "*", default-features = false }
