[package]
name = "tests"
version.workspace = true
edition.workspace = true

[dev-dependencies]
casper-types = { workspace = true, features = ["std"] }
casper-event-standard.workspace = true
cep85 = { path = "../contracts/contract" }
cep85-test-contract = { path = "../contracts/test-contract" }
casper-engine-test-support = { git = "https://github.com/casper-network/casper-node.git", default-features = false }
casper-execution-engine = { git = "https://github.com/casper-network/casper-node.git", default-features = false }
casper-storage = { git = "https://github.com/casper-network/casper-node.git", default-features = false }
