name: ci-casper-cep-85-client

on:
  push:
    branches:
      - 'dev'
      - 'feat-*'
      - 'release-*'

  pull_request:
    branches:
      - 'dev'
      - 'feat-*'
      - 'release-*'

jobs:
  client-build:
    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [20.x]
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential wabt

      - name: Setup
        run: make prepare

      - name: Prepare WASMs
        run: make setup-test

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a #v3.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        working-directory: ./client-js
        run: npm install

      - name: Copy & convert WASMs
        working-directory: ./client-js
        run: npm run wasms:convert

      - name: Audits
        working-directory: ./client-js
        run: npm audit --omit=dev

      - name: Lints
        working-directory: ./client-js
        run: npm run lint

      - name: Test
        working-directory: ./client-js
        run: npm test
