name: ci-casper-cep-85-client

on:
  push:
    branches:
      - 'dev'
      - 'feat-*'
      - 'release-*'

  pull_request:
    branches:
      - 'dev'
      - 'feat-*'
      - 'release-*'

jobs:
  client-build:
    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [20.x]
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      # # Replace by above service with docker image of stable 2.0
      # - name: Clone casper-nctl-2-docker repository
      #   run: |
      #     git clone https://github.com/gRoussac/casper-nctl-2-docker.git

      # - name: Build and start the service
      #   run: |
      #     cd casper-nctl-2-docker
      #     make build-start 2.0
      #     cd ..

      # - name: Wait for the service to be ready
      #   run: |
      #     echo "Waiting for the service to be ready on port 11101..."
      #     for i in {1..30}; do # wait for up to 30 seconds
      #       if nc -z localhost 11101; then
      #         echo "Service is up!"
      #         echo "Wait 45s for nctl to boot and create keys"
      #         sleep 45  # - name: wait for up to 45 seconds for an era like
      #         break
      #       fi
      #       echo "Waiting..."
      #       sleep 1
      #     done

      #     # Check if the service is still not ready after 30 seconds
      #     if ! nc -z localhost 11101; then
      #       echo "Service did not start in time!"
      #       exit 1
      #     fi

      # # - name: List files in the users directory
      # #   run: |
      # #     echo "Listing files in the users directory of the service container..."
      # #     docker exec ${{ job.services.casper-nctl.id }} ls /app/casper-nctl/assets/net-1/users/

      # # - name: List files in user-1 directory
      # #   run: |
      # #     echo "Listing files in ./assets/users/user-1/:"
      # #     ls -la ./casper-nctl-2-docker/assets/users/user-1/

      # # WARNING: These accounts, and their private keys, are now publicly known.
      # # Any funds sent to them on Mainnet or any other live network WILL BE LOST.
      # - name: Set SECRET_KEY_USER_1 and SECRET_KEY_USER_2 environment variables
      #   run: |
      #     echo "SECRET_KEY_USER_1=$(sed -n '2p' ./casper-nctl-2-docker/assets/users/user-1/secret_key.pem)" >> $GITHUB_ENV
      #     echo "SECRET_KEY_USER_2=$(sed -n '2p' ./casper-nctl-2-docker/assets/users/user-2/secret_key.pem)" >> $GITHUB_ENV

      # - name: Delete user-1 directory
      #   run: |
      #     echo "Deleting ./casper-nctl-2-docker directories..."
      #     sudo rm -rf ./casper-nctl-2-docker

      # - name: Print GITHUB_ENV
      #   run: |
      #     echo "Contents of GITHUB_ENV:"
      #     cat $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Swatinem cache
        uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c #v1.4.0

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential wabt

      - name: Setup
        run: make prepare

      - name: Prepare WASMs
        run: make setup-test

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a #v3.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        working-directory: ./client-js
        run: npm install

      - name: Copy & convert WASMs
        working-directory: ./client-js
        run: npm run wasms:convert

      - name: Audits
        working-directory: ./client-js
        run: npm audit --omit=dev --audit-level=moderate

      - name: Lints
        working-directory: ./client-js
        run: npm run lint

      - name: Test
        working-directory: ./client-js
        run: npm test
