name: publish-cep-85-contracts

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-contract-tarball:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential wabt

      - name: Setup
        run: make prepare

      - name: Build wasm contracts
        run: make build-contract

      - name: Create tarball
        run: ./ci/package_wasm.sh

      - name: Upload tarball to release
        uses: svenstaro/upload-release-action@133984371c30d34e38222a64855679a414cb7575 #v2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/ci_package_wasm_${{ github.ref_name }}/cep-85-wasm.tar.gz
