name: publish-casper-cep85-client

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [20.x]

    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential wabt

      - name: Setup
        run: make prepare

      - name: Prepare WASMs
        run: make setup-test

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5b949b50c3461bbcd5a540b150c368278160234a #v3.4.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        working-directory: ./client-js
        run: npm install

      - name: Copy & convert WASMs
        working-directory: ./client-js
        run: npm run wasms:convert

      - name: Publish to NPM
        working-directory: ./client-js
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
